import { initGenericGrid } from 'src/app/shared/genericUtils';
import { HEIGHT, WIDTH } from '../models/grid';

// A maze is defined generically as a grid where an obstacle corresponds to true and no obstacle corresponds to false
// Mazes generated by these algorithms don't concern themselves with the type of obstacles placed
export type Maze = boolean[][];

type Row = boolean[];

// Generate a maze where each tile has a 30% chance of being an obstacle
export function genRandomMaze(): Maze {
  const densityThreshold = 0.3;
  const maze = genEmptyMaze();

  maze.forEach((row: Row) => fillRowRandomly(row, densityThreshold));

  return maze;
}

// Generate a maze where each tile is an obstacle, useful for obstacles that aren't complete barriers
export function genFilledGridMaze(): Maze {
  return initGenericGrid(HEIGHT, WIDTH, () => true);
}

// Randomly fill in a row of obstacles where each tile has a 30% chance of being an obstacle
function fillRowRandomly(row: Row, densityThreshold: number): void {
  for (let tile = 0; tile < row.length; tile++) {
    if (Math.random() < densityThreshold) {
      row[tile] = true;
    }
  }
}

// Generate a maze with no obstacles
function genEmptyMaze(): Maze {
  return initGenericGrid(HEIGHT, WIDTH, () => false);
}
